---
- name: Ensure a unique Diffie Hellman Group is generated
  command: openssl dhparam -out {{nginx_conf_dir}}/dhparams.pem 2048
  args:
    creates: "{{nginx_conf_dir}}/dhparams.pem"
  tags: [configuration,nginx,mymy]

